### ISSUE TITLE
Unos bankovnih izvoda u bazu podataka

### ISSUE THREAD

**Issue by antunsimic** [antunsimic/digitalnivodomjer#18]
_Rok 12.4. odnosi se na skroz gotov i funkcionalan program. Da bi se ostavilo dovoljno vremena za popravke koda, prvu verziju (funkcionalnu koliko god je moguće) potrebno je objaviti **10.4**._

Potrebno je unijeti podatke iz bankovnog izvoda (.OTP) datoteke u bazu podataka  [vodomjeri.db](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/Vodomjeri?csf=1&web=1&e=ipDCo0), u tablicu Uplata. Za bolje razumijevanje baze podataka, možete pogledati ER dijagram ([ER_dijagram.pdf](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/Vodomjeri?csf=1&web=1&e=ipDCo0)).
Za svaki podatak koji program za parsiranje datoteke izvoda učitava u varijable postoji odgovarajući stupac u tablici. 
Program mora moći odjednom unijeti sve bankovne izvode iz jednog direktorija.

**Comment by DadoCres** [comment]
Može primjer baze?
