### ISSUE TITLE
Integracija programa i baze podataka u Flask

### ISSUE THREAD

**Issue by antunsimic** [antunsimic/digitalnivodomjer#29]
_Rok 25.4. odnosi se na skroz gotovu i funkcionalnu Flask aplikaciju. Da bi se ostavilo dovoljno vremena za popravke koda, prvu verziju (funkcionalnu koliko god je moguće) potrebno je objaviti **24.4**._

Potrebno je integrirati bazu podataka i dosada napravljene Python programe u Flask. Za pomoć mogu se pročitati upute ispod na engleskom jeziku. Što se tiče primarnih i stranih ključeva, ER dijagram baze podataka može se naći na OneDrive-u.
 

### Steps to Consolidate Python Programs into Flask

1. **Set Up Flask Framework:**
   Start by setting up the basic structure of a Flask application. This includes creating a main application file (usually `app.py` or similar) and organizing your project directory appropriately.

   ```python
   from flask import Flask
   from flask_sqlalchemy import SQLAlchemy

   app = Flask(__name__)
   app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///vodomjeri.db'  # Adjust the path as needed
   db = SQLAlchemy(app)
   ```

2. **Organize Code into Modules:**
   Your existing Python programs likely contain functions and classes that perform specific tasks (e.g., parsing files, generating reports, interacting with the database). Organize these into modules that can be imported into your Flask application. For example, you might have:

   - `models.py` for your database models.
   - `utilities.py` for utility functions like file parsing.
   - `services.py` for business logic.

3. **Integrate Database Models:**
   Use SQLAlchemy, which is integrated with Flask via Flask-SQLAlchemy, to define your database models. These models will represent the tables in your SQLite database.

   ```python
   # models.py
   from . import db

   class User(db.Model):
       id = db.Column(db.Integer, primary_key=True)
       username = db.Column(db.String(80), unique=True, nullable=False)
       # Additional fields as needed
   ```

4. **Create Application Endpoints:**
   Define routes in your Flask application that will handle different functionalities. For example, an endpoint to upload files, another to generate reports, etc.

   ```python
   @app.route('/upload', methods=['POST'])
   def upload_file():
       # Logic to handle file upload
       pass
   ```

5. **Migrate Core Algorithms:**
   Each core functionality you've developed (e.g., file parsing, report generation) should be adapted into this Flask framework. This might mean:

   - Turning scripts into callable functions that can be triggered by Flask routes.
   - Adapting command-line interfaces to web interfaces.
   - Ensuring that output (e.g., reports) can be returned via web responses or saved directly from web inputs.

6. **Testing:**
   Once integrated, thoroughly test each component to ensure it works within the web context. Use Flask's test client to simulate requests and responses.

7. **Error Handling and Logging:**
   Implement proper error handling and logging within your Flask application to manage and debug issues as they arise.

8. **Documentation:**
   As you consolidate and modify your code, keep documentation updated. This is crucial for maintenance and for new developers who may join your project.

### Advantages of Consolidation
- **Centralization of Code:** All functionalities are in one place, simplifying management and scalability.
- **Easier Transition to Production:** A single Flask application is easier to deploy and manage in a production environment.
- **Enhanced Collaboration:** Team members can work more collaboratively when all functionalities are integrated and consistent.

This approach not only streamlines your development process but also prepares your project for future enhancements, such as adding user authentication, integrating more complex database relationships, or scaling up to handle more traffic or data.

**Comment by fmartinkovic** [comment]
Funkcionalnosti implementiramo u Flask da bi se mogle koristiti unutar web aplikacije?

Također, je li SQLAlchemy substitucija za sqlite3 knjižnicu koju smo do sada koristili?

**Comment by fmartinkovic** [comment]
Što točno dođe `REFERENCES "Mujo"("ID_KORISNIK")` pri tablici Uplata?

Pitam jer se SQLAlchemy zbog toga ne može spojiti na tu tablicu.

**Comment by fmartinkovic** [comment]
Također, zašto su neki stupci za datume tipa `INTEGER` ili `REAL`, ne bi li trebali biti `TEXT`?
