### ISSUE TITLE
Obrada datoteka očitanja Maddalena

### ISSUE THREAD

**Issue by antunsimic** [antunsimic/digitalnivodomjer#3]
U Pythonu treba napraviti program koji će uspješno izvući informacije iz datoteka koje generira uređaj za daljinsko očitavanje vodomjera talijanske tvrtke Maddalena. Program mora raditi na 3 priložene datoteke: [Madd(...).xlsx](https://uniri-my.sharepoint.com/:f:/g/personal/antun_simic_student_uniri_hr/Esk8f234-6REqAij7YGpL5gBruj5IisvNJ-4DTpd-epyJw?e=hJkSaS). Željeni rezultat rada programa jest odvojeno posjedovanje i ispravno klasificiranje parametara iz datoteke kao što je definirano u dokumentu [Maddalena-opis.docx](https://uniri-my.sharepoint.com/:f:/g/personal/antun_simic_student_uniri_hr/Esk8f234-6REqAij7YGpL5gBruj5IisvNJ-4DTpd-epyJw?e=hJkSaS).
Osim navedenih stupaca, potrebno je za svaki slog / redak i zabilježiti još jedan podatak / stupac, naziva datum_m3. Njegova vrijednost je datum zadnjeg dana u mjesecu. Mjesec se određuje stupcem _timestamp_ (vrijeme čitanja) tako da se uzima prethodni mjesec. Npr. ako je vrijednost čitanja / _timestamp_ u nekom retku 01.02.2024 20:41:33, stupac datum_m3 mora imati vrijednost 31.1.2024.

Molim vas da za neočekivano velike probleme s kojima se budete suočili prilikom rješavanja ovog zadatka (problemi čije je rješenje bilo rezultat istraživanja ili prilikom čijeg rješavanja ste dosta toga naučili) uz Vaš deliverable još dostavite i dokument u kojem biste opisali Vaš proces od otkrivanja do rješavanja tog problema.

Deliverable neka bude uploadan u mapu [submissions](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/prijedlog_projekta/Vodomjeri/submissions?csf=1&web=1&e=2hab8f), u pripadajući tjedan.

**Comment by fmartinkovic** [comment]
Iz Excel datoteka se filtriraju podaci definirani u datoteci maddalena-opis.docx, a potom se isti stavljaju u novu Excel datoteku ili bazu podataka?
@antunsimic
