### ISSUE TITLE
Obrada datoteka bankovnih izvoda

### ISSUE THREAD

**Issue by antunsimic** [antunsimic/digitalnivodomjer#4]
U Pythonu treba napraviti program koji će uspješno izvući informacije iz datoteka bankovnih izvoda. Program mora raditi na 3 priložene datoteke: [IZV(...).OTP](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/prijedlog_projekta/Vodomjeri/datoteke_za_ucitavanje?csf=1&web=1&e=H3TzBn). Željeni rezultat rada programa jest odvojeno posjedovanje i ispravno klasificiranje parametara iz datoteke kao što je definirano u dokumentu [izv-opis.pdf](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/prijedlog_projekta/Vodomjeri/datoteke_za_ucitavanje?csf=1&web=1&e=H3TzBn).
Konkretnije, iz datoteke izvoda potrebno je učitati sljedeće atribute: 

- Redni broj izvatka (IZ903RBIZV)
- Datum izvatka (IZ903DATUM) 
- za svaki slog 905: informacije koje ga jednoznačno određuju

Informacije koje je potrebno zabilježiti za svaki slog 905 su:
- Račun platitelja - (IZ905RNPRPL),  
- Naziv platitelja - (IZ905NAZPRPL) 
- Adresa platitelja - (IZ905ADRPRPL) 
- Sjedište platitelja - (IZ905SJPRPL) 
- Datum izvršenja - (IZ905DATIZVR) 
- Iznos – (IZ905IZNOS) 
- Poziv na broj primatelja - (IZ905PNBPR)  
- Opis plaćanja - (IZ905OPISPL) 
- redni broj stavke izvoda

Vrijednost zadnjeg atributa određuje se jednostavno rednim brojem tog sloga 905 unutar datoteke u odnosu na ostale slogove 905: prvi takav imat će redni broj stavke izvoda 1, drugi slog 905 će biti 2, itd.

Hint: za svako od polja u u dokumentu izv-opis.pdf definirana je njegova duljina, kao i početno i krajnje mjesto (stupci OD, DO, BROJ MJESTA)

Molim vas da za neočekivano velike probleme s kojima se budete suočili prilikom rješavanja ovog zadatka (problemi čije je rješenje bilo rezultat istraživanja ili prilikom čijeg rješavanja ste dosta toga naučili) uz Vaš deliverable još dostavite i dokument u kojem biste opisali Vaš proces od otkrivanja do rješavanja tog problema.

Deliverable neka bude uploadan u mapu [submissions](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/prijedlog_projekta/Vodomjeri/submissions?csf=1&web=1&e=2hab8f), u pripadajući tjedan.

**Comment by DadoCres** [comment]
Popravljeno

**Comment by DadoCres** [comment]
> redni broj stavke izvoda (slogova 905) treba biti lista, da ne bi bio pregažen svaki put. Svaki slog 905 mora imati svoj pridruženi redni broj, baš kao što ima svoj npr. račun platitelja.

Popravljeno
