### ISSUE TITLE
WBS za stadij projekta: web aplikacija

### ISSUE THREAD

**Issue by antunsimic** [antunsimic/digitalnivodomjer#6]
Napraviti Work Breakdown Structure za stadij projekta: oblikovanje programa u web aplikaciju. Imati na umu:

- koristit će se React
- web aplikacija će nuditi vizualizaciju potrošnje kroz grafove, mogućnost filtriranja i sortiranja stanova po potrošnji

Work Breakdown Structure treba se temeljiti na istraživanju i kao takav trebao bi biti što je moguće više realističan. Sasvim je u redu odabrati specifične tehnologije / alate koji bi bili korišteni ako će to olakšati izradu konkretnijeg WBS-a.
Deliverable: dokument koji sadrži WBS i nekoliko linkova koji su poslužili kao inspiracija / izvor informacija pri izradi.

Molim vas da za neočekivano velike probleme s kojima se budete suočili prilikom rješavanja ovog zadatka (problemi čije je rješenje bilo rezultat istraživanja ili prilikom čijeg rješavanja ste dosta toga naučili) uz Vaš deliverable još dostavite i dokument u kojem biste opisali Vaš proces od otkrivanja do rješavanja tog problema.

Deliverable neka bude uploadan u mapu [submissions](https://uniri-my.sharepoint.com/:f:/r/personal/antun_simic_student_uniri_hr/Documents/6.%20semestar/Programsko%20in%C5%BEenjerstvo/projekt/prijedlog_projekta/Vodomjeri/submissions?csf=1&web=1&e=2hab8f), u pripadajući tjedan.

**Comment by KarloPaic** [comment]
[webapp_WBS_document.pdf](https://github.com/antunsimic/digitalnivodomjer/files/14829301/webapp_WBS_document.pdf)
![webapp_WBS_standalone](https://github.com/antunsimic/digitalnivodomjer/assets/95750952/1f7359f9-30fc-44cc-90c0-f7abb193d4b6)

Šaljem i ovdje za slučaj da bude potrebno
